azure-pipelines.yml, src/common/zscore/ZscoreWeb/script.py, src/common/zscore/cgmzscore/__init__.py, src/common/zscore/cgmzscore/test_cgmzscore.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifact-plaincnn-height/src/test/test_preprocessing.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/test/test_preprocessing.py
**Motivation:** `flake8` checks that code is linted according to the common Python [PEP](https://www.python.org/dev/peps/pep-0008/) rules. By adding this to our CI pipeline we keep the code linted correctly.
**Changes:**
- add flake8 lint check to our pipeline
- resolve few flake8 errors
Future work:
- speed up (currently 3min18sec) the build by improve caching of azure pipeline
=> Add flake8 to pipeline

src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifact-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/constants.py
**Motivation**
During https://github.com/Welthungerhilfe/cgm-ml/pull/104, we restructured the repository.
In this process REPO_DIR became broken. 
**Implementation**
This is the fix such that REPO_DIR is in the root of the repository again
=> Bugfix REPO_DIR

pytest.ini, src/common/eval/Evaluate_models.ipynb, src/common/eval/Evaluate_multiartifact_model.ipynb, src/common/eval/eval_utils.py, src/common/eval/tests/test_eval_utils.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/config.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/model.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py
Tackles https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/38
Changes: 
- Fix: actually use model head, not just a single Dense layer
- Change output format from `.h5` to `.ckpt` (This is default suggestion for TF2, .h5 has caused error `h5py: "RuntimeError: Unable to create link (name already exists)"` https://github.com/tensorflow/tensorflow/issues/36650#issuecomment-585517731)
- Adjust `Evaluate_models.ipynb` to multiartifact
- Evaluate all test-data (prepare code using a bad performing model)
- Refactor creating dataframe in `Evaluate_models.ipynb`
=> Adjust Model Evaluation to multiartifact (Functional API)

src/common/depthmap_toolkit/convertpcd2depth.py, src/common/depthmap_toolkit/depthmap.py, src/common/depthmap_toolkit/utils.py
This PR adds a simple triangulation into depthmap toolkit. Export OBJ feature now adds into OBJ file vertex indices which changes the OBJ format from pointcloud to mesh. This enables better visualization of the quality of the captured data (especially useful during testing new devices)
[User story](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/296)
Test was done by visualizing exported data. Steps to reproduce the test:
* python convertpcd2depth.py _path_to_folder_with_pcd_file_
* python toolkit.py output
* click on export OBJ
* open export/output0.obj in Blender or any another 3D editor
=> Depthmap toolkit triangualtion into export obj added

src/common/zscore/azure-pipelines.yml
**Bug**: I found that zscore pipeline runs unintendedly, e.g., https://github.com/Welthungerhilfe/cgm-ml/pull/125
Currently, every PR commit builds the pip packages.
The file trigger seems doesn't seem to work.
To improve the situation, let's only run this on master and releases. Also only run this once for 1 python version
=> Fix: Only push when master or release

src/common/depthmap_toolkit/depthmap.py
Depthmap toolkit has a feature to write coordinates and distances between the clicks in depthmap. However due to swapped axis it did not work correctly.
[bug report](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/335)
* checking if undefined areas returned correct values
* measuring objects with known dimensions
=> Depthmap toolkit measure click function fixed

src/common/eval/Evaluate_multiartifact_model.ipynb, src/common/eval/eval_utils.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/model.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/preprocessing.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/utils.py
**Motivation**: `train.py` was quite long. 
**Solution:** In order to alleviate this problem, code is put into other modules.
**Changes:**
* Move create_samples() function into preprocessing.py
* Move get_base_model() and download_pretrained_model() into model.py
* Put callbacks into utils() function
* Remove code for activation because unused
**Check if this still works:**
- I ran the pipeline locally
- I made a run on a cluster, see [this run](https://ml.azure.com/experiments/id/ae599009-2154-4928-b46e-676866e12c61/runs/q3-depthmapmultiartifactlatefusion-plaincnn-height-95k-debug_1603878685_5b8e9d6e?wsid=/subscriptions/9b82ecea-6780-4b85-8acf-d27d79028f07/resourceGroups/cgm-ml-prod/providers/Microsoft.MachineLearningServices/workspaces/cgm-azureml-prod&tid=006dabd7-456d-465b-a87f-f7d557e …
=> Refactor multiartifactlatefusion experiment code

requirements.txt
This PR will avoid this warning when running `pytest`: 
```
=============================================================================================================================== warnings summary ===============================================================================================================================
/Users/markus/.virtualenvs/env_p_3/lib/python3.7/site-packages/_pytest/junitxml.py:417
/Users/markus/.virtualenvs/env_p_3/lib/python3.7/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
_issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, …
```
=> Update pytest pip dependency

src/common/depthmap_toolkit/convertpcd2depth.py, src/common/depthmap_toolkit/pcd2depth.py, src/common/depthmap_toolkit/toolkit.py
Modified the pcd2depth.process() function into two functions now. pcd2depth. prcoess() , it now returns the depthmap array and pcd2depthmap.write_depthmap() writes the depthmap into .depth file.
User story # (US link): none
After making changes, ran these file to check the proper functionality
=> Modify the depthmap toolkits to return depthmaps as array and write them into .depth file into tow diffrent function

src/common/evaluation/QA/test-pipeline.yml
**Problem:** 
- The master build of cgm-ml seems to be broken, see https://github.com/Welthungerhilfe/cgm-ml/runs/1441345384
- we have 3 pipelines in this repo
- `cmg-ml`: `azure-pipelines.yml` flake8 and pytest
- `cmg-ml (1)`: `src/common/evaluation/QA/test-pipeline.yml` evaluate models
- `cmg-ml (2)`: `src/common/zscore/azure-pipelines.yml` release z-score
- pushing to master triggers all pipelines, but `cmg-ml (1)` is broken
**Solution**: disable `cmg-ml (1)`
There is an option to disable a pipeline in azure devops: https://dev.azure.com/cgmorg/ChildGrowthMonitor/_build?definitionId=3
=> Disable qa pipeline (because it is broken)

src/common/rgbd_toolkit/rgbd.py
**Motivation:** The RGBD code is still quite unstable, so it would be good to be able to disable multiprocessing. 
**Solution:** a debug flag helps to disable multiprocessing
**How to use this**
```bash
python rgbd.py --input input_dir/ --output output_dir/ --debug
```
=> Introduce rgbd debug flag

src/common/evaluation/QA/eval-depthmap-height/src/qa_config.py, src/common/evaluation/QA/test-pipeline.yml
Bug: model evaluation pipeline was broken.
This PR fixes this. 
How did I check this works:
- I added a commit that enables the pipeline
- I saw that the pipeline ran (see github Commits tab above in this PR)
- I disabled the pipeline so it doesn't always run for all future PR
=> Fix eval/ vs evaluation/ dir bug

requirements.txt
**Motivation:** install pip dependencies faster by taking binary packages
I measured and this reduces installation time from 10.5min to 8.5min.
=> Use psycopg-binary instead psycopg

requirements.txt
**Motivation:** importlib2 is a backport, so should not be needed for Python3
=> Remove importlib2

src/common/evaluation/QA/environment.yml, src/common/evaluation/QA/eval-depthmap-height/eval_main.py, src/common/evaluation/QA/eval-depthmap-height/src/constants.py, src/common/evaluation/QA/eval-depthmap-height/src/evaluate.py, src/common/evaluation/QA/eval-depthmap-height/src/qa_config_height.py, src/common/evaluation/QA/eval-depthmap-height/src/utils.py, src/common/evaluation/QA/test-pipeline.yml
**Findings:** Mounting the data slows down prediction time because the data has to be fetched over the network. It is a lot faster to fully download the data before starting to predict.
**Changes:**
- Download instead of mounting (to speed up)
- Use batch size of 1024 instead of 256 (to speed up)
- remove caching since we use every sample only once in model evaluation (unlike in training)
- add some print statements to mention how fast the prediction
- Use TF2.3 and py3.7
**Details about speed measurements**
Before this PR: The run takes 32m 10.37s ([Run 204](https://ml.azure.com/experiments/id/4347c355-aa9d-4482-b7d9-2130b9aa7c44/runs/QA-pipeline_1606901417_9803b4cd?wsid=/subscriptions/9b82ecea-6780-4b85-8acf-d27d79028f07/resourceGroups/cgm-ml-prod/providers/Microsoft.MachineLearningServi …
=> Speed-up of model eval

src/common/evaluation/QA/test-pipeline.yml
This was an issue introduced by https://github.com/Welthungerhilfe/cgm-ml/pull/197/
=> Disable model eval pipeline for every PR

src/common/evaluation/QA/environment.yml
Resolve warning: `Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies by adding pip into conda dependencies`
=> Remove conda warning

src/common/depthmap_toolkit/depthmap.py
The visualisation of confidence was not nature for human eye (overbright==black). I fixed it by inverting overbright value.
The first picture overbright==black
The second picture overbright==white
Connected to bug ticket https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/635/
=> Better confidence visualisation for depthmap toolkit

.flake8, src/analyses/reliability/location/location_utils.py, src/common/evaluation/QA/eval-standardisation-test/src/utils.py, src/common/model_utils/preprocessing.py, src/common/result_generation/tests/test_blur.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/model.py
In the beginning of cgm-ml, we needed to setup a lightweight check. Now the repo has matured and we can follow pep8 more closely
Re-Enable:
- E252 missing whitespace around parameter equals
- I100 import order
- I101 import order
- E701
- E302: Expected 2 blank lines, found 1
=> Follow pep8 more closely

.github/workflows/continous-integration.yml
Problem: We trigger the build twice which is not necessary
Solution: The `push` build will already show up in the PR.
=> Remove double trigger

src/common/evaluation/QA/eval-standardisation-test/src/qa_config_height.py, src/common/evaluation/QA/eval-standardisation-test/src/qa_config_weight.py, src/common/evaluation/QA/eval-standardisation-test/src/utils.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight.py, src/common/evaluation/QA/eval_depthmap_models/src/utils.py, src/common/evaluation/eval_utils.py
Motivation: CSV files that we output should be readable by stakeholders.
Changes
- reduce places where names are repeated
- rename:
- Rename '_front' to '_standingfront'
- Rename '_360' to '_standing360'
- Rename '_back' to '_standingback'
=> Rename _front to _standingfront (and similar)

pytest.ini
**Problem:** 
- unit tests are accessing Azure resources (a postgres database), but they should be independent of internet access
- therefore unit tests can not just be run locally
**Solution:** 
- Ignore dataset test
- this test can be added back later if it doesn't require internet access
Also this is faster in CI:
- [before](https://github.com/Welthungerhilfe/cgm-ml/runs/1682627546) duration: `7min11sec` 
- after duration: `39sec`
=> Exclude broken unit test

src/common/zscore/azure-pipelines.yml
Motivation: [github has renamed master branch to main branch](https://github.com/github/renaming). In order to be consistent, we will rename, too.
For individual contributors: You can update your local setup like this:
=> Rename master to main in codebase

src/common/evaluation/QA/environment.yml, src/common/evaluation/QA/eval_depthmap_models/eval_configs.sh, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_filter.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py, src/common/evaluation/QA/test-pipeline.yml
**Status quo:** We changed Service connection / Service Principle to the new tenant. Now the pipeline will always run in the new tenant. 
**Changes:**
- `setuptools` and `wheel` are needed now otherwise the conda installation in the AzureML docker build fails
- run experiements again in new tenant (they get new run IDs)
- change experiment names and run ids so they get found in the new tenant
- Disable filter config because it would not yet work
Future work: we have to bring the standing/lying classification model in the new tenant so we can reference it in the pipeline again (@prajurock )
=> Enable eval pipeline in new tenant

src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py, src/common/evaluation/QA/eval_depthmap_models/src/utils.py, src/common/evaluation/eval_utils.py
**Our code looks like this:**
```python
paths = new_paths_evaluation
dataset = tf.data.Dataset.from_tensor_slices(paths)
dataset_norm = dataset.map(lambda path: tf_load_pickle(path, DATA_CONFIG.NORMALIZATION_VALUE))
dataset_norm = dataset_norm.filter(...)  # newly introduced
```
This poses the problem that if we use the `new_paths_evaluation` after the filtering, they haven't been filtered yet.
**Solution:** When we filter the dataset, we also update the paths.
**Future work:**
In the future, datasets should not have 'delete' scans/artifacts in them.
=> Handle 'delete' key by filtering the tf.dataset

src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifact-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifact-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/constants.py, src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/train_notebook.ipynb, src/models/Unsupervised/Autoencoder/q4-anomalydetection-ae/src/constants.py, src/models/Unsupervised/Autoencoder/q4-anomalydetection-ae/train_notebook.ipynb
**Motivation:** It is easy to miss to update pip requirements in notebooks. When using modules, it is easier to see changes in git and to find all occurrences in the code.
=> Put pip packages to constants.py instead of notebook

src/common/evaluation/QA/eval_depthmap_models/src/utils.py
True, False Negative, False Positive added in stunting confusion matrix.
User story #[ (US link)](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/770)
#Result
=> Percentage added in confusion matrix

src/common/evaluation/QA/eval_depthmap_models/eval_configs.sh, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_filter.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height_no_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight_no_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/utils.py
**User story:** https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/812
**Changes:**
- ran existing weight experiment `q4-depthmap-plaincnn-weight-95k` in new tenant
- update eval pipeline to track new experiment/run/name
**Before(old tenant):**
**Now([new tenant](https://ml.azure.com/experiments/id/5f0723c5-648a-47f7-ab72-b3c0afccaeb2?wsid=/subscriptions/9b5bbfae-d5d1-4aae-a2ca-75159c0c887d/resourcegroups/cgm-ml-prod-we-rg/workspaces/cgm-ml-prod-we-azml&tid=3a27c573-ec1a-4734-9cd3-3208af51794b))**
=> Weight model in new tenant

src/common/evaluation/QA/eval_depthmap_models/src/qa_config_filter.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height_no_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight_dropout.py, src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight_no_dropout.py, src/common/evaluation/QA/test-pipeline.yml
**Motivation:** It is hard to keep the overview with so many output assets in the evaluation pipeline runs.
**Solution:** Split the results in several output directories so we can keep the overview, one directory per config we run
Note: This separates weight results from height results
=> Put weight into different output dir

src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py, src/common/evaluation/QA/eval_depthmap_models/src/utils.py
Speed the Model evaluation pipeline
1. Multiprocessing
2. Using apply in place of the loop
3. Using different function(zscore_lhfa)
4. Loading the data for zscore once 
[Bug-](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/863)
Tested locally:
For 20 QR code
Before suggested change:- 43 sec
After suggested change:- 9 sec
After removing multiprocessing:- 20 sec.
=> Speed up the confusion matrix in model evaluation pipeline

.github/workflows/continous-integration.yml
Hotfix
The cache was somehow broken leading to the wrong environment being cached. 
[The cache cannot be cleared](https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions). 
Instead we now version the cache key and will change it whenever this happens again
=> Fix flake8 / github actions cache

src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/train.py, src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/train_notebook.ipynb
**Motivation**: After our update to py3.7, we potentially mounted instead of downloading because we used our own code to download
**Solution**: The [azureml documentation](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.dataset_consumption_config.datasetconsumptionconfig?view=azure-ml-py#methods) tells what to do. We adhere to that.
Done for 3 experiments that we maintain actively:
- `src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/`
- `src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/`
- `src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/`
=> Fix training download dataset

README.md
Binder added in Github Respoitories so that anyone can visualize notebooks without cloning and setting up the local environment.
=> Binder added in readme.md

src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height_no_dropout.py
Coverage results have improved, therefore updating [wiki page for real-world height results] ([Run](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_build/results?buildId=2781&view=artifacts&pathAsName=false&type=publishedArtifacts))(https://dev.azure.com/cgmorg/ChildGrowthMonitor/_wiki/wikis/ChildGrowthMonitor.wiki/149/Eval-depthmaps-height-real-world)
Future work:
- we might want to deploy this model
=> Adjust config file from Run 4 to Run 7

docs/Onboarding.ipynb, experimental/pose_estimation/QA/poseest_notebook.ipynb, experimental/pose_estimation/commonpy.py, old/cgm-dataset/create-dataset/create_dataset.py, src/analyses/reliability/Standing-laying/Evaluation_standing_laying.ipynb, src/analyses/reliability/Standing-laying/utils.py, src/common/evaluation/QA/auth.py, src/common/evaluation/QA/eval-standardisation-test/auth.py, src/common/evaluation/QA/eval-standardisation-test/eval_notebook.ipynb, src/common/evaluation/QA/eval-standardisation-test/src/utils.py, src/common/evaluation/QA/eval_depthmap_models/auth.py, src/common/evaluation/QA/eval_depthmap_models/eval_main.py, src/common/evaluation/QA/eval_depthmap_models/src/utils.py, src/data_utils/data_access_with_labels.ipynb, src/data_utils/data_visualisation/data_visualisations.ipynb, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/model.py, src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/deploy.ipynb, src/models/GAPNet/GAPNet-height/s1-gapnet-height/code/deploy.ipynb, src/models/PersonLab/PersonLabV1/code/deploy.ipynb, src/models/pointnet/pointnet-height/pointnet-20190708/code/deploy.ipynb, src/models/pointnet/pointnet-height/pointnet-20190806/code/deploy.ipynb
**Motivation**: It is confusing to switch between two different names for the same thing
**Solution:** As `workspace` occurs more often in the codebase, we rename `ws` to `workspace` to stick to one consistent way of usage
=> Rename ws to workspace to be more consistent

src/common/depthmap_toolkit/utils.py
Depthmap toolkit has a bug in exporting OBJ. The function should use a pose from the depthmap to align the model (floor should have constant Y). This PR solves this bug.
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1030
I converted depthmap with visible floor into OBJ and validated that the floor is correctly oriented:
=> fix export obj orientation in depthmap toolkit

codecov.yml
Example of a comment: 
Motivation: This comment is not super useful, I suggest to keep codecov more quiet and having it too look when we want to see it, but not always
=> Avoid codecov comment

src/common/depthmap_toolkit/README.md, src/common/depthmap_toolkit/depthmap.py, src/common/depthmap_toolkit/utils.py
Updated camera pose calculation (scan type v1.0), visualisation of surface normal in world coordinates and repeating pattern visualisation which might help to solve ML models HW dependency.
Scan type v1.0 updates:
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1059
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1047
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1024
The depthmaps from Samsung Note10+, Huawei P30 Pro and Lenovo Phab 2 Pro were all tested with moving/rotating camera to confirm validity of normals orientation, surface pattern. Examples:
Samsung Note10+
Lenovo Phab 2 Pro
Huawei P30 Pro
=> Depthmap toolkit visualisation

src/common/depthmap_toolkit/depthmap.py, src/common/depthmap_toolkit/utils.py
This PR adds RGB mapping when using OBJ export in depthmap toolkit. Using that we can get a textured model from RGBD data.
Note: in the second image there is missing part of body because from the device perspective it was not visible (covered by a hand).
User story # (US link)
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1223
I did a visual check using data captured by Huawei, Lenovo and Samsung:
* Huawei produces high quality RGBD alignment and exported models look perfect
* Lenovo has a good RGBD alignment but depthmap toolkit does not support unordered data (which means there is needed to set as input a single depthmap and single rgb frame to prevent mistmatch). Exported models look very good
* Samsung does not have a valid lens calibration and because of it the …
=> depthmap toolkit exports textured OBJs

src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/train_notebook.ipynb
**Motivation:** There was the idea of training on a subset of training data, e.g. only standing children.
**Solution**: In order to allow this CNN and M-CNN should parse a list with codes (aka scan steps) and only use the ones for training that are configured
=> Filter for training codes

src/common/depthmap_toolkit/utils.py
Exported OBJ from depthmap toolkit had for odd triangles wrong vertex order which caused in some programs incorrect shading or missing triangles:
User story https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1307
=> Depthmap toolkit vertex order fixed when exporting OBJ

src/common/depthmap_toolkit/depthmap.py, src/common/depthmap_toolkit/toolkit.py
This PR adds an example how to calculate an angle between camera and floor with depthmap toolkit:
* 90 degrees - camera is pointing to ceiling
* 0 degrees - camera is pointing to horizont (parallel to floor)
* -90 degrees - camera is pointing to floor
* The input data has to use scan type v0.9 or higher
* If the phone was exposed during scanning to a strong magnet then the values might be wrong
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1050
It was tested by multiple checking math formula and validating output values.
=> Depthmap toolkit logs angle between camera and floor

src/common/depthmap_toolkit/exporter.py, src/common/depthmap_toolkit/toolkit.py, src/common/depthmap_toolkit/visualisation.py
The floor alignment is necessary to make the work with the exported model user friendly.
Additionally I made visualisation.py independent of matplotlib, this way it could be used with another rendering systems.
User story https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1477
By exporting multiple OBJs and checking if the floor alignment is correct (using Blender)
=> Depthmap exporter revision: floor alignment

src/common/depthmap_toolkit/tests/test_depthmap.py, src/common/depthmap_toolkit/tests/test_visualisation.py, src/common/depthmap_toolkit/visualisation.py
This refactor enables to use the visualisations in other scripts. E.g. to get normal map call:
```
output = np.zeros((dmap.width, dmap.height, 3))
render_normal(output, 0, dmap)
```
=> Depthmap toolkit - Visualisation refactor

src/common/cgmcore/file_utils.py, src/common/cgmcore/tests/test_file_utils.py, src/common/evaluation/QA/eval_depthmap_models/src/test_evaluate.py, src/common/evaluation/tests/test_uncertainty_utils.py, src/common/evaluation/tests/test_utils.py
**Motivation:** `copy_dir` is used not only in `evaluate.py` but also outside. The location of the function and the test seem too specific.
**Solution:** Move the function to src/common/cgmcore/file_util.py
=> Move test_copy_dir() to cgmcore/

.github/workflows/continous-integration.yml, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config_deep_ensemble.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config_weight.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/config.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/config_weight.py, src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/train_notebook.ipynb, src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/config.py, src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/train_notebook.ipynb, src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/sl_config.py, src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/train_notebook.ipynb
**Changes:**
- introduce config parameter CLUSTER_NAME in training configs
- use CLUSTER_NAME in train_notebooks
- Re-do github actions virtualenv creation (and cache it)
**Time Measurements**
| Run       | Comment        | Epoch duration  |
| -------- |:-------------:| -----:|
| Run11     | K80, BS=64, baseline                  |  837s | 
| [Run 16](https://ml.azure.com/experiments/id/4d4b47ee-b56c-44ca-8966-1a8d77201ece/runs/training-junkyard-multigpu_1625831777_496c6dc5?wsid=/subscriptions/9b5bbfae-d5d1-4aae-a2ca-75159c0c887d/resourceGroups/cgm-ml-prod-we-rg/providers/Microsoft.MachineLearningServices/workspaces/cgm-ml-prod-we-azml&tid=3a27c573-ec1a-4734-9cd3-3208af51794b)   | M60, BS64, baseline           | 448s | 
| Run17     | M60, BS=128, baseline                  |  452s  | 
| …
=> Use cluster with different GPU type: NVIDIA M60

src/common/depthmap_toolkit/EDA_RGBD_segmentationCV.ipynb, src/common/depthmap_toolkit/convertdepth2pcd.py, src/common/depthmap_toolkit/depthmap.py, src/common/depthmap_toolkit/depthmap_utils.py, src/common/depthmap_toolkit/exporter.py, src/common/depthmap_toolkit/pcd2depth.py, src/common/depthmap_toolkit/scan_toolkit.ipynb, src/common/depthmap_toolkit/tests/test_depthmap.py, src/common/depthmap_toolkit/tests/test_visualisation.py, src/common/depthmap_toolkit/toolkit.py, src/common/depthmap_toolkit/visualisation.py, src/common/reliability/background_segm/tests/test_maskrcnn_resizeimage.py
**CR:** https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1543
**Changes:**
- Prevent redundant `parse_depth()` calculation by maintaining an np.array `depthmap_arr`
- Improve Depthmap constructor interface: now support `create_from_file` (ZIP) and `create_from_array` (np.array)
- Introduce `Depthmap.create_from_array()`
- Introduce `EDA_RGBD_segmentationCV.ipynb` to analyze RGBD pickle files with depthmap toolkit
- Fix: toolkit fails to ignore hidden files like `.DS_Store`
- Introduce `is_google_tango_resolution()`
- Remove unused `convert_3d_to_2d`
- Use cgm-ml/data/export as default export directory instead of using code directories
- Making export more robust
- Making toolkit.py callable from cgm-ml dir: `python src/common/depthmap_toolkit/toolkit.py …
=> Refactor to re-use CV-based image segmentation and normals
