Welthungerhilfe/cgm-ml

- README.md
> Clarify how to create dataset

- blur_faces.py
This addition has the following functionality:
- Skips processing for already existing files/folders.
- Detects faces & blurs detected region using Gaussian Blur in rgb images
- Copies other files and folders while preserving original directory structure
> 53 Remove PII Info by blurring faces

- cgm_database/08_Fusion_Evaluation.ipynb
- cgm_database/command_update_fusion.py
- cgm_database/command_update_segmentation.py
- cgm_fusion/calibration.py
- cgm_fusion/fusion.py
- cgm_fusion/utility.py
The pull request merges the current state of the background segmentation. 
I might enhance the visualization of the sensor fusion in an additional pull request.
> 586 remove background

- cgm_database/schema.sql
> new database schema

- cgm_database/schema.sql
Reverts Welthungerhilfe/cgm-ml#65
> Revert "new database schema"

- cgm_database/generate_depth_from_pcd.py
- cgm_fusion/fusion.py
- cgm_fusion/generate_depth_from_pcd.py
- cgm_fusion/utility.py
The depth maps are generated within the sensor fusion approach. The work done should not affect any other parts of the framework. 
Closing US 1217.
> 1217 depth map

- depthmap_toolkit/README.md
- depthmap_toolkit/camera_calibration.txt
- depthmap_toolkit/convertall.py
- depthmap_toolkit/convertdepth2pcd.py
- depthmap_toolkit/convertpcd2depth.py
- depthmap_toolkit/depthmap.py
- depthmap_toolkit/pcd2depth.py
- depthmap_toolkit/toolkit.py
- depthmap_toolkit/utils.py
This toolkit provides conversion from new cgm-scanner format to PCD and back + few useful utils.
> Added depthmap toolkit

- Reliabilty/pcd_rgb_visualisation/pcd_rgb_posenet_model.ipynb
- Reliabilty/pcd_rgb_visualisation/visualizeutils.py
Work item :-[Evaluate PersonLab feet/face visibility vs. error of results](https://dev.azure.com/cgmwhh/ChildGrowthMonitor/_workitems/edit/1758/
)
Work done
best / worst examples are  visualized
both the images for pose prediction and
the artifacts (pcd) for result generation
> Visualization of pcd and rgb along with posenet

- src/common/depthmap_toolkit/convertdepth2pcd.py
- src/common/depthmap_toolkit/convertpcd2depth.py
- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/pcd2depth.py
- src/common/depthmap_toolkit/toolkit.py
- src/common/depthmap_toolkit/utils.py
**Motivation of this PR:**
[PEP8](https://www.python.org/dev/peps/pep-0008/) is a commonly use style guide for Python code. 
`src/common/depthmap_toolkit` was not adhering to this style.
**Changes:**
- To use a common style, I ran: `autopep8 --in-place --aggressive --aggressive --recursive "./src/common/depthmap_toolkit/"`
- manually fix minor pep8 issues
**Outcome:** `flake8 src/common/depthmap_toolkit` shows no errors anymore
> Pep8ify depthmap_toolkit

- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifact-plaincnn-height/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py
The changes are made for 3 current experiments: 
- q3-depthmap-plaincnn-height
- q3-depthmapmultiartifact-plaincnn-height
- q3-depthmapmultiartifactlatefusion-plaincnn-height
Changes:
- Remove unused lines
- Rename qrcode_path variable
> Clean train script

- src/common/zscore/README.rst
- src/common/zscore/azure-pipelines.yml
- src/common/zscore/setup.py
US 61 -https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/62
Aim- Create a new pipeline for cgmzscore which will create and upload package to PyPI.org.
> Zscore pipeline 

- src/common/depthmap_toolkit/toolkit.py
This PR is a compile fix of following commit:
https://github.com/Welthungerhilfe/cgm-ml/commit/3241374d9e734cc91a59d16f9b8b58caeb89933f
> Depthmap toolkit line indent fix

- .coveragerc
- .gitignore
- azure-pipelines.yml
User story https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/161
> Add code coverage

- src/common/depthmap_toolkit/README.md
- src/common/depthmap_toolkit/convertdepth2pcd.py
- src/common/depthmap_toolkit/convertpcd2depth.py
- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/pcd2depth.py
- src/common/depthmap_toolkit/toolkit.py
- src/common/depthmap_toolkit/utils.py
**Motivation** The code's readability can be slightly improved
**Changes:**
- Format as code in README
- Sort imports
> Make depthmap_toolkit more pythonic

- azure-pipelines.yml
- requirements.txt
**Motivation** The pip requirements are duplicated in our codebase. 
**Solution** The CI pipeline will use the same requirements as the developer. These requirements are in `requirements.txt`
> Install from requirements.txt in azure pipeline

- src/common/eval/QA/test-pipeline.yml
- src/common/zscore/azure-pipelines.yml
**Problem** The zscore pipeline and test/qa pipeline run for every PR. This is not necessary and complicates unrelated PRs.
**Changes:**
- diable zscore pipeline and test/qa pipeline for PRs
- fix indent for test/qa pipeline for PRs
Notice that this PR only has 3 checks instead of 5 checks.
> Run special-purpose pipelines less often

- src/common/rgbd_toolkit/cgm_fusion/calibration.py
- src/common/rgbd_toolkit/cgm_fusion/fusion.py
- src/common/rgbd_toolkit/cgm_fusion/normals_with_open3d.py
- src/common/rgbd_toolkit/cgm_fusion/utility.py
- src/common/rgbd_toolkit/get_timestamps.py
- src/common/rgbd_toolkit/rgbd.py
joined work with @prajurock 
**Motivation**: The RGBD code does not yet adhere to our coding standards. 
**Solution**: This PR improves readabilitity. 
**Changes:**
- Sort imports, Use global variable for height and weight, remove commented code
- Clean docstrings
- Make global variables uppercase, polish import
- Rename to use snake case, Fix import order
- Use does_path_belong_to_codes() function to remove code duplication
- Make small adjustments to `fusion.py` and `calibration.py`
- Refactor `rgbd.py` and `get_timestamp.py`
We ran the command `python rgbd.py --input $CGM_ML_DIR/data/anon-bmz-version5.0_incomplete/qrcode/ --output $CGM_ML_DIR/data/anon-bmz-version5.0_incomplete_converted/qrcode/`
> Refactor RGBD

- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config.py
**Issue**: Some values in config.py are not necessary and can therefore be removed.
> Remove parts of the config not used by the experiment

- src/common/rgbd_toolkit/rgbd.py
RGB timestamp is sorted along with path.
> Sorting the RGB timestamp

- .gitignore
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
We define CONFIG.TARGET_INDEXES but we never used it in this experiment. This PR fixes this issue
> Fix bug: configuration was ignored

- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
**Motivation** Hyperparameters can be stored in config.py. 
Solution: also store the flag for dropout in the config.py
> Use configuration parameter for dropout

- src/common/depthmap_toolkit/convertdepth2pcd.py
- src/common/depthmap_toolkit/convertpcd2depth.py
- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/pcd2depth.py
- src/common/depthmap_toolkit/toolkit.py
- src/common/depthmap_toolkit/utils.py
- src/common/evaluation/QA/eval-standardisation-test/src/utils.py
- src/data_utils/HonorView_DataAnalysis.ipynb
- Rename camelCase to snake_case
- Remove unused function
- Sort imports
I check that this still works by running 
```
python convertdepth2pcd.py honor/
python convertpcd2depth.py export
python toolkit.py output
```
> Improve depthmap toolkit

- src/common/model_utils/preprocessing.py
Changes:
- Order imports
- add type annotations
> Polish model utils

- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
**Motivation** Remove unused code
> Remove unused activation maps code

- azure-pipelines.yml
- requirements.txt
Build was broken, this PR fixes it
Explanations:
- https://stackoverflow.com/a/36785114/5497962
- https://github.com/Greenwolf/social_mapper/issues/25
> Fix py3.6 build

- requirements.txt
- src/common/evaluation/QA/eval-standardisation-test/src/qa_config_height.py
- src/common/evaluation/QA/eval-standardisation-test/src/qa_config_weight.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight.py
- src/common/evaluation/eval_utils.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/config_weight.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifact-plaincnn-height/src/config.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/config.py
- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/config.py
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/sl_config.py
**Motivation:** Less code, more readability
> Replace dotdict with Bunch

- src/common/evaluation/QA/eval_depthmap_models/combine_results.py
- src/common/evaluation/QA/eval_depthmap_models/eval_main.py
- src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py
- src/common/evaluation/QA/eval_depthmap_models/src/utils.py
- src/common/evaluation/QA/test-pipeline.yml
The branch was used to add the functionlit of multimodel evaluation and combining the  multiple csv of different models into 
a single csv file.
User story 584 (https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/584)
A new function is added to the pipeline combine_result.py. The pipeline ran successfully and the combined result CSV was produced for multiple height models.
Wiki Link for the results that were produced using this pipeline:
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_wiki/wikis/ChildGrowthMonitor.wiki/149/Evaluation-of-ML-models-depthmaps-height-realworld
> Model evaluation on real-world data

- src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py
- src/common/evaluation/QA/eval_depthmap_models/src/utils.py
- src/common/evaluation/QA/test-pipeline.yml
**Motivation:** Besides model evaluation on age (https://github.com/Welthungerhilfe/cgm-ml/pull/186), we can now easily evaluate on:
- sex ('male' or 'female')
- good/bad scan (quality of the scan)
**Changes:**
- enable sex analysis
- enable good/bad analysis
**Findings**
(As expected) The accuracy is greater on good scans. Therefore we should strive to get good scans:
There is little or no difference between female and male scans:
**Results:**
- https://dev.azure.com/cgmorg/ChildGrowthMonitor/_build/results?buildId=2166&view=artifacts&pathAsName=false&type=publishedArtifacts
**Do before merge:** Revert `pr: none`
> Analyze sex and goodbad

- src/common/evaluation/QA/eval-standardisation-test/src/qa_config_height.py
- src/common/evaluation/QA/eval-standardisation-test/src/qa_config_weight.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_42c4ef33.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_cb44f6db.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height.py
- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_weight.py
- src/common/evaluation/QA/test-pipeline.yml
Changes:
- Revert changes introduced in #228
> Revert configs

- src/common/evaluation/QA/eval_depthmap_models/src/utils.py
Pipeline fixed after fail in #247
> Pipeline fixed

- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/deploy.ipynb
Standing-laying classifier endpoint deployed as endpoints
User story # ([US link](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_sprints/backlog/ChildGrowthMonitor%20Team/ChildGrowthMonitor/2021.Q1/Sprint%201?workitem=669))
Endpoint is deployed in Azure ML
> Standing-laying endpoint deployment

- src/common/evaluation/QA/eval_depthmap_models/src/evaluate.py
First step of: https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/863
> Speed up pipeline by commenting confusion matrix calculation

- requirements.txt
**Motivation:** Align with `src/common/evaluation/QA/environment.yml` where we use the newer version already
> Upgrade matplotlib

- src/common/evaluation/QA/eval_depthmap_models/src/utils.py
- src/common/zscore/cgmzscore/cgmzscore.py
Changes:
- Remove redundant brackets
- Improve readability by removing line breaks
> Polish zscore code

- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/constants.py
- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/train_notebook.ipynb
Successor of https://github.com/Welthungerhilfe/cgm-ml/pull/270/
> Update multitask experiment

- src/common/evaluation/QA/eval_depthmap_models/src/utils.py
> change display labels

- environment_train.yml
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/config.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/constants.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/model.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/train_notebook.ipynb
**Changes:**
- update to also use py3.7 training (Add opencv which is required here)
- update to new tenant (change pretrained run)
**Future work:** 
- evaluate in new tenant
> Train Multiartifact experiment in new tenant

- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py
> Remove debug size

- .github/workflows/continous-integration.yml
- README.md
Codecov report added in cgm-ml repository
#130 
All checks passed in GitHub workflow
> CodeCov in cgm-ml repository

- src/data_utils/dataset_EDA/anon-depthmap-95k/EDA_anon-depthmap-95k.ipynb
**Motivation**: It turns out that we have some unrealistic values in our training dataset. This can lead to the model learning something wrong
**Solution**: Integrate sanity checks in EDA notebooks, s.t. we find out when preparing the dataset.
**Changes:**
- look for unrealistic height values
- look for out-of-distribution pixel values (all pixel values are between 0 and 10), but not for 1 qrcode
> Analyze unrealistic values in 95k dataset

- README.md
- src/common/zscore/README.rst
1.Package health added for cgmzscore library
2. Gihtub action banner added
> New banner added

- src/common/evaluation/QA/eval_depthmap_models/src/tests/test_utils.py
- src/common/evaluation/QA/eval_depthmap_models/src/utils.py
- Unit test of `calculate_percentage_confusion_matrix` added
- Round added in `calculate_percentage_confusion_matrix` function
- Unit test of `test_draw_uncertainty_goodbad_plot` added
> Increase the code coverage and modified the functions

- old/cgm-dataset/create-dataset/utils.py
- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/pcd2depth.py
- src/common/depthmap_toolkit/utils.py
- src/data_utils/HonorView_DataAnalysis.ipynb
**Changes:**
- Rename `file` -> `f` (file is a Python keyword)
- Rename `calibration` -> `CALIBRATION` (global variable)
- Rename `dir` to `dir_path` (dir is a Python keyword)
- Refactor style: `camelCase` to `snake_case`
- Fix wrong naming: `convert_2d_to_3d` -> `convert_3d_to_2d`
**For reviewers:**
- please test if the depthmap toolkit still works as expected (since we don't have unit tests)
> Refactor depthmap-toolkit

- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/model.py
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/sl_config.py
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/sl_constants.py
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/train.py
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/src/train_util.py
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/train_notebook.ipynb
Standing/laying classifier added in new tenant  with new code
https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1079
https://ml.azure.com/experiments/id/e008bb91-602d-479c-9347-aa217542aa40/runs/q4-rgb-plaincnn-classifaction-standing-lying-8k_1617693180_689ec560?wsid=/subscriptions/9b5bbfae-d5d1-4aae-a2ca-75159c0c887d/resourcegroups/cgm-ml-prod-we-rg/workspaces/cgm-ml-prod-we-azml&tid=3a27c573-ec1a-4734-9cd3-3208af51794b
> Standing/laying classifier retrain in new tenent 

- src/models/CNNDepthMap/CNNDepthMap-height/q2milestone-cnndepthmap-height/code/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-cnndepthmap-resnet-height/code/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/lr_find-plaincnn.ipynb
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/src/train.py
Changes:
- Improve reference to model_utils
- Remove unused `tf_flip()` code
> Refactor code

- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/src/train.py
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/train_notebook.ipynb
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/train_notebook.ipynb
- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/train_notebook.ipynb
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/train_notebook.ipynb
**Changes:**
* Put imports onto the top of a notebook and order them into 3 categories: stdlib, 3rd party, own
> Refactor training notebook imports

- src/common/evaluation/evaluation_analysis/Analyze_worst_scans.ipynb
- src/data_utils/dataset_EDA/data_utilities.py
The notebook is used to analyze some of the worst-performing scans for depthmap based models for height measurement
User story #999 (https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/999)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
>  analyse worst scans

- src/data_utils/dataset_EDA/anon-rgbd-5k/EDA_anon-rgbd-5kscans.ipynb
Identify outliers in dataset. Integrate data_utilities - find_outlier_qrcodes function
User story # https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1119/
> 1119 RGBD outliers

- src/common/depthmap_toolkit/convertdepth2pcd.py
- src/common/depthmap_toolkit/convertpcd2depth.py
- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/toolkit.py
**Changes:**
- rename variable names
- make global vars `width` and `height` local
- Polish minor things
> Refactor depthmap toolkit

- src/common/depthmap_toolkit/convertdepth2pcd.py
- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/toolkit.py
For reviewers: I wasn't able to verify if this works. Please check if toolkit.py still works in the same way as before
> Remove plt from arguments

- src/common/depthmap_toolkit/utils.py
**Motivation:** `python toolkit.py` did not work for me anymore
**Solution:** define matrix in the else branch
> Define matrix variable in else-branch, Make matrix contain floats

- src/common/depthmap_toolkit/pcd2depth.py
- src/common/depthmap_toolkit/utils.py
> Remove global width/height

- src/common/evaluation/QA/eval-standardisation-test/src/evaluate.py
- src/common/evaluation/QA/eval-standardisation-test/src/utils.py
- src/common/rgbd_dataset/rgbd_dataset.py
Tackling https://github.com/Welthungerhilfe/cgm-ml/issues/328
> Refactor dataset code

- README.md
**To reviewers:** What else did you wish was documented to get you (or any contributor) started?
> Add helpful explanations for repo structure and contributors

- src/common/evaluation/QA/eval_depthmap_models/src/qa_config_height_deep_ensemble.py
- src/common/evaluation/eval_utilities.py
- src/common/evaluation/tests/test_eval_utils.py
There was the potential to improve the eval utilities
Issues: qa_config_height_deep_ensemble.py takes 2h51min [Run](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_build/results?buildId=3623&view=artifacts&pathAsName=false&type=publishedArtifacts)
**User story**: none
**Changes:**
- Extract `calc_accuracy()`
- Extract `calculate_accuracies()` and `calculate_accuracies_on_age_buckets()`
- Reduce the time of the pipeline from 5hours to 3hour 40min (by only running 2 models in the ensemble)
- test `calculate_accuracies`
- test `calculate_accuracies_on_age_buckets `
- test `calculate_performance_age`
Unit tests
> Refactor eval utilities

- src/analyses/EDA/covid19_survey_analysis/constants.py
Motivation
The [E501 long line check was added in the flake8](https://github.com/Welthungerhilfe/cgm-ml/pull/354)  after the merge of [covid19 data analyses branch](https://github.com/Welthungerhilfe/cgm-ml/pull/354). So checks got broken in main branch due to long line error in covid19 analysis.
This branch fixes long line E501 error in covid19 data analyses
User story [1334](https://dev.azure.com/cgmorg/ChildGrowthMonitor/_workitems/edit/1334
)
> Fixed long line flake8 issue

- .github/workflows/continous-integration.yml
**Solution:** Don't let CI fail when codecov upload fails
> Don't let CI fail when codecov upload fails

- src/data_utils/dataset_EDA/anon-depthmap-95k/EDA_anon-depthmap-95k.ipynb
- src/data_utils/dataset_EDA/data_utilities.py
> Issue336 floor instead round eda

- src/data_utils/dataset_generation_databricks/SETUP.md
- src/data_utils/dataset_generation_databricks/databricks_dataset_creation.py
- updated setup file after setting up QA
- updated code to use SAS tokens to connect to storage account
> Update setup databricks

- src/common/depthmap_toolkit/depthmap.py
- src/common/depthmap_toolkit/depthmap_utils.py
- src/common/depthmap_toolkit/tests/test_depthmap.py
- src/common/depthmap_toolkit/tests/test_visualisation.py
- src/common/depthmap_toolkit/visualisation.py
Faceblur of the detected standing child added. It uses the highest point of the child and blur all pixels in distance less than 25cm.
Visual test on multiple input data
> Depthmap - faceblur added

- src/models/CNNDepthMap/CNNDepthMap-height/2021q2-depthmap-resnet-height/train_notebook.ipynb
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmap-plaincnn-height/train_notebook.ipynb
- src/models/CNNDepthMap/CNNDepthMap-height/q3-depthmapmultiartifactlatefusion-plaincnn-height/train_notebook.ipynb
- src/models/CNNDepthMap/CNNDepthMap-multitask/q4-depthmap-plaincnn-multitask/train_notebook.ipynb
- src/models/CNNRGB/CNNRGB-standing_laying/q4-rgb-standing-laying/train_notebook.ipynb
> remove environment value from imported file
